### ISSUE TITLE
Missing day 3

### ISSUE THREAD

**Issue by flaflouu** [Caeles12/AdventOfCode2024#1]
where is it?
![hippo](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnBvdmlnemMxcTVkZDBlaW1qNDZkMWs5Y2VqajRiamQ0M3JpN3MyMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gPbhyNB9Vpde0/giphy.webp)

**Comment by Caeles12** [comment]
done in 5791943bab1b756fb72a7144daa9cfb001f547ed
